testContent: devTest2
test: ${testContent}

spring:
  redis:
    host: 192.168.1.152
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1

durid:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://192.168.1.156:5432/boss-mcc-test
  username: postgres
  password: '000000'
# 下面为连接池的补充设置，应用到上面所有数据源中
# 初始化大小，最小，最大
  initialSize: 5
  minIdle: 5
  maxActive: 20
# 配置获取连接等待超时的时间
  maxWait: 60001
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000
# 配置一个连接在池中最小生存的时间，单位是毫秒
  minEvictableIdleTimeMillis: 300000
  #validationQuery: SELECT 1 FROM BASE_SMS_LOG #校验SQL，PROD环境可以配置一个
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
# 打开PSCache，并且指定每个连接上PSCache的大小
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  filters: stat,wall,log4j

server:
  port: 8085

HttpRequestService:
  checkurl: "http://139.196.240.53:8001/"
  isGoToClassUrl: "http://139.196.240.53:8001/"
  signInUrl: "http://139.196.240.53:8003/"